select count(*) from regextest where name like '%Strasse%';
select count(*) from regextest where regex(name, 'Strasse');
select count(*) from regextest where dfaregex(name, 'Strasse');
select count(*) from regextest where hyperscanregex(name, 'Strasse');
select count(*) from regextest where match(name, '(Strasse|Str\.).*(8[0-9]{4})');
select count(*) from regextest where regex(name, '(Strasse|Str\.).*(8[0-9]{4})');
select count(*) from regextest where dfaregex(name, '(Strasse|Str\.).*(8[0-9]{4})');
select count(*) from regextest where hyperscanregex(name, '(Strasse|Str\.).*(8[0-9]{4})');
select count(*) from regextest where match(name, '[0-9]+(USD|EUR|GBP)');
select count(*) from regextest where regex(name, '[0-9]+(USD|EUR|GBP)');
select count(*) from regextest where dfaregex(name, '[0-9]+(USD|EUR|GBP)');
select count(*) from regextest where hyperscanregex(name, '[0-9]+(USD|EUR|GBP)');
select count(*) from regextest where match(name, '[A-Za-z]{3}\:[0-9]{4}');
select count(*) from regextest where regex(name, '[A-Za-z]{3}\:[0-9]{4}');
select count(*) from regextest where dfaregex(name, '[A-Za-z]{3}\:[0-9]{4}');
select count(*) from regextest where hyperscanregex(name, '[A-Za-z]{3}\:[0-9]{4}');
